import os
from datetime import timedelta


class Config(object):
    DEBUG = True
    SQLALCHEMY_TRACK_MODIFICATIONS = False


class ProductionConfig(Config):
    PORT = os.getenv("PORT")
    USER_DB_HOST = os.getenv("USER_DB_HOST")
    USER_DB_NAME = os.getenv("USER_DB_NAME")
    USER_DB_USER = os.getenv("USER_DB_USER")
    USER_DB_PASSWORD = os.getenv("USER_DB_PASSWORD")
    USER_DB_PORT = os.getenv("USER_DB_PORT")
    USER_SQLALCHEMY_DATABASE_URI = "mysql+pymysql://HOST:PASSWORD@/DATABASE?ADDRESS"
    USER_SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv("SQLALCHEMY_TRACK_MODIFICATIONS")

    ROOM_DB_HOST = os.getenv("ROOM_DB_HOST")
    ROOM_DB_NAME = os.getenv("ROOM_DB_NAME")
    ROOM_DB_USER = os.getenv("ROOM_DB_USER")
    ROOM_DB_PASSWORD = os.getenv("ROOM_DB_PASSWORD")
    ROOM_DB_PORT = os.getenv("ROOM_DB_PORT")
    ROOM_SQLALCHEMY_DATABASE_URI = "mysql+pymysql://HOST:PASSWORD@/DATABASE?ADDRESS"
    ROOM_SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv("SQLALCHEMY_TRACK_MODIFICATIONS")

    MAIL_SERVER = "smtp.gmail.com"
    MAIL_PORT = 465
    MAIL_USERNAME = ""
    MAIL_PASSWORD = ""
    MAIL_USE_TLS = False
    MAIL_USE_SSL = True
    MAIL_SECRET_KEY = "SECRET KEY"
    SECURITY_PASSWORD_SALT = ""

    JWT_ACCESS_TOKEN_EXPIRES_TIME = os.getenv("JWT_ACCESS_TOKEN_EXPIRES")
    if JWT_ACCESS_TOKEN_EXPIRES_TIME:
        JWT_ACCESS_TOKEN_EXPIRES = timedelta(
            hours=int(os.getenv("JWT_ACCESS_TOKEN_EXPIRES"))
        )
    JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
    JWT_COOKIE_SECURE = os.getenv("JWT_COOKIE_SECURE")
    JWT_BLACKLIST_ENABLED = os.getenv("JWT_BLACKLIST_ENABLED TRUE")
    JWT_BLACKLIST_TOKEN_CHECKS = os.getenv("JWT_BLACKLIST_TOKEN_CHECKS")

    JSON_AS_ASCII = False

    GOOGLE_CLOUD_STORAGE_BUCKET_NAME = ""


class DevelopmentConfig(Config):
    PORT = os.getenv("PORT")
    USER_DB_HOST = os.getenv("USER_DB_HOST")
    USER_DB_NAME = os.getenv("USER_DB_NAME")
    USER_DB_USER = os.getenv("USER_DB_USER")
    USER_DB_PASSWORD = os.getenv("USER_DB_PASSWORD")
    USER_DB_PORT = os.getenv("USER_DB_PORT")
    USER_SQLALCHEMY_DATABASE_URI = f"mysql+pymysql://{USER_DB_USER}:{USER_DB_PASSWORD}@{USER_DB_HOST}:{USER_DB_PORT}/{USER_DB_NAME}"
    USER_SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv("SQLALCHEMY_TRACK_MODIFICATIONS")

    ROOM_DB_HOST = os.getenv("ROOM_DB_HOST")
    ROOM_DB_NAME = os.getenv("ROOM_DB_NAME")
    ROOM_DB_USER = os.getenv("ROOM_DB_USER")
    ROOM_DB_PASSWORD = os.getenv("ROOM_DB_PASSWORD")
    ROOM_DB_PORT = os.getenv("ROOM_DB_PORT")
    ROOM_SQLALCHEMY_DATABASE_URI = f"mysql+pymysql://{ROOM_DB_USER}:{ROOM_DB_PASSWORD}@{ROOM_DB_HOST}:{ROOM_DB_PORT}/{ROOM_DB_NAME}"
    ROOM_SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv("SQLALCHEMY_TRACK_MODIFICATIONS")

    MAIL_SERVER = "smtp.gmail.com"
    MAIL_PORT = 465
    MAIL_USERNAME = ""
    MAIL_PASSWORD = ""
    MAIL_USE_TLS = False
    MAIL_USE_SSL = True
    MAIL_SECRET_KEY = ""
    SECURITY_PASSWORD_SALT = ""

    JWT_ACCESS_TOKEN_EXPIRES_TIME = os.getenv("JWT_ACCESS_TOKEN_EXPIRES")
    if JWT_ACCESS_TOKEN_EXPIRES_TIME:
        JWT_ACCESS_TOKEN_EXPIRES = timedelta(
            hours=int(os.getenv("JWT_ACCESS_TOKEN_EXPIRES"))
        )
    JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
    JWT_COOKIE_SECURE = os.getenv("JWT_COOKIE_SECURE")
    JWT_BLACKLIST_ENABLED = os.getenv("JWT_BLACKLIST_ENABLED TRUE")
    JWT_BLACKLIST_TOKEN_CHECKS = os.getenv("JWT_BLACKLIST_TOKEN_CHECKS")

    JSON_AS_ASCII = False

    GOOGLE_CLOUD_STORAGE_BUCKET_NAME = ""


class StagingConfig(Config):
    PORT = os.getenv("PORT")
    USER_DB_HOST = os.getenv("USER_DB_HOST")
    USER_DB_NAME = os.getenv("USER_DB_NAME")
    USER_DB_USER = os.getenv("USER_DB_USER")
    USER_DB_PASSWORD = os.getenv("USER_DB_PASSWORD")
    USER_DB_PORT = os.getenv("USER_DB_PORT")
    USER_SQLALCHEMY_DATABASE_URI = f"mysql+pymysql://{USER_DB_USER}:{USER_DB_PASSWORD}@{USER_DB_HOST}:{USER_DB_PORT}/{USER_DB_NAME}"
    USER_SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv("SQLALCHEMY_TRACK_MODIFICATIONS")

    ROOM_DB_HOST = os.getenv("ROOM_DB_HOST")
    ROOM_DB_NAME = os.getenv("ROOM_DB_NAME")
    ROOM_DB_USER = os.getenv("ROOM_DB_USER")
    ROOM_DB_PASSWORD = os.getenv("ROOM_DB_PASSWORD")
    ROOM_DB_PORT = os.getenv("ROOM_DB_PORT")
    ROOM_SQLALCHEMY_DATABASE_URI = f"mysql+pymysql://{ROOM_DB_USER}:{ROOM_DB_PASSWORD}@{ROOM_DB_HOST}:{ROOM_DB_PORT}/{ROOM_DB_NAME}"
    ROOM_SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv("SQLALCHEMY_TRACK_MODIFICATIONS")

    MAIL_SERVER = "smtp.gmail.com"
    MAIL_PORT = 465
    MAIL_USERNAME = ""
    MAIL_PASSWORD = ""
    MAIL_USE_TLS = False
    MAIL_USE_SSL = True
    MAIL_SECRET_KEY = ""
    SECURITY_PASSWORD_SALT = ""

    JWT_ACCESS_TOKEN_EXPIRES_TIME = os.getenv("JWT_ACCESS_TOKEN_EXPIRES")
    if JWT_ACCESS_TOKEN_EXPIRES_TIME:
        JWT_ACCESS_TOKEN_EXPIRES = timedelta(
            hours=int(os.getenv("JWT_ACCESS_TOKEN_EXPIRES"))
        )
    JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
    JWT_COOKIE_SECURE = os.getenv("JWT_COOKIE_SECURE")
    JWT_BLACKLIST_ENABLED = os.getenv("JWT_BLACKLIST_ENABLED TRUE")
    JWT_BLACKLIST_TOKEN_CHECKS = os.getenv("JWT_BLACKLIST_TOKEN_CHECKS")

    JSON_AS_ASCII = False

    GOOGLE_CLOUD_STORAGE_BUCKET_NAME = ""
