version: '3'

services:
  airbnb-service-backend:
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - "80:80"
    depends_on:
      - airbnb-service-db
    networks:
      - airbnb-service-backend
    volumes:
      - .:/app
  airbnb-service-db:
    platform: linux/x86_64
    image: library/mysql:5.7
    container_name: airbnb-service-db
    ports:
      - "3306:3306"
    volumes:
      - ./resources/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./resources/local_only_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=ehdrmfl123
    networks:
      - airbnb-service-backend
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    networks:
      - airbnb-service-backend
networks:
  airbnb-service-backend:
