FROM python:3.8

ENV WORK_ENV PRODUCTION

ENV PORT 8080

ENV USER_DB_HOST airbnb-service-db
ENV USER_DB_NAME airbnb_user
ENV USER_DB_USER root
ENV USER_DB_PASSWORD ""
ENV USER_DB_PORT 3306
ENV USER_DB_POOL_RECYCLE 60
ENV SQLALCHEMY_TRACK_MODIFICATIONS FALSE

ENV ROOM_DB_HOST airbnb-service-db
ENV ROOM_DB_NAME airbnb_host
ENV ROOM_DB_USER root
ENV ROOM_DB_PASSWORD ""
ENV ROOM_DB_PORT 3306
ENV ROOM_DB_POOL_RECYCLE 60
ENV SQLALCHEMY_TRACK_MODIFICATIONS FALSE

ENV MAIL_SERVER = 'smtp.gmail.com'
ENV MAIL_PORT = 465
ENV MAIL_USERNAME = ''
ENV MAIL_PASSWORD = ''
ENV MAIL_USE_TLS = False
ENV MAIL_USE_SSL = True
ENV MAIL_SECRET_KEY = ''
ENV SECURITY_PASSWORD_SALT = ''

ENV MAIL_SECRET_KEY ''
ENV SECURITY_PASSWORD_SALT ''

ENV JWT_SECRET_KEY ''
ENV JWT_COOKIE_SECURE True
ENV JWT_ACCESS_TOKEN_EXPIRES 1
ENV JWT_BLACKLIST_ENABLED TRUE
ENV JWT_BLACKLIST_TOKEN_CHECKS ['access', 'refresh']

ENV GOOGLE_APPLICATION_CREDENTIALS /app/resources/key.json
ENV GOOGLE_CLOUD_STORAGE_BUCKET_NAME airbnb_cloud_storage

RUN mkdir /app
VOLUME /app
COPY . /app
WORKDIR /app

RUN pip install pipenv
RUN pipenv install --dev --deploy --system
ENV PORT 8080
EXPOSE 8080
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "app:app"]
